name: Run Code Tests

on:
  push:
    paths:
      - "submissions/**"
  pull_request:
    paths:
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect Changed Files
        id: changed-files
        run: |
          BEFORE_COMMIT="${{ github.event.before }}"
          if [ -z "$BEFORE_COMMIT" ] || ! git cat-file -e "$BEFORE_COMMIT"^{commit}; then
            BEFORE_COMMIT=$(git rev-parse HEAD~1)
          fi
          
          CHANGED_FILES=$(git diff --name-only "$BEFORE_COMMIT" HEAD | grep '^submissions/' || true)
          echo "Detected changed files: $CHANGED_FILES"

          if [ -z "$CHANGED_FILES" ]; then
            echo "No file changes detected. Skipping tests."
            exit 0
          fi

          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Determine File Type
        run: |
          for file in $CHANGED_FILES; do
            case "$file" in
              *.c) echo "language_C=true" >> $GITHUB_ENV ;;
              *.cpp) echo "language_CPP=true" >> $GITHUB_ENV ;;
              *.py) echo "language_Python=true" >> $GITHUB_ENV ;;
              *.java) echo "language_Java=true" >> $GITHUB_ENV ;;
            esac
          done

      - name: Install Dependencies
        run: |
          sudo apt update
          [[ "$language_C" == "true" ]] && sudo apt install -y gcc
          [[ "$language_CPP" == "true" ]] && sudo apt install -y g++
          [[ "$language_Python" == "true" ]] && sudo apt install -y python3
          [[ "$language_Java" == "true" ]] && sudo apt install -y openjdk-17-jdk

      - name: Compile and Run C Tests
        if: env.language_C == 'true'
        run: |
          gcc submissions/*.c tests/test.c -o test_runner
          if [ $? -ne 0 ]; then exit 1; fi
          ./test_runner | tee test_results_C.log

      - name: Compile and Run C++ Tests
        if: env.language_CPP == 'true'
        run: |
          g++ submissions/*.cpp tests/test.cpp -o test_runner_cpp
          if [ $? -ne 0 ]; then exit 1; fi
          ./test_runner_cpp | tee test_results_CPP.log

      - name: Run Python Tests
        if: env.language_Python == 'true'
        run: |
          python3 tests/test.py | tee test_results_Python.log
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Compile and Run Java Tests
        if: env.language_Java == 'true'
        run: |
          javac submissions/*.java tests/Test.java
          if [ $? -ne 0 ]; then exit 1; fi
          java -cp submissions:tests Test | tee test_results_Java.log

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results_*.log
